# Site settings
title:          leaveittogod0123's blog
title_separator : " : "
description:    "leaveittogod0123 Personal Website"
baseurl:        ""
url:            https://leaveittogod0123.github.io/

# Author
author:
  name:         Yoseph Noh
  url:          https://leaveittogod0123.github.io/
  email:        leaveittogod0123@gmail.com

# Build settings
markdown:       kramdown

language: 'ko-KR'


# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Google Analutics
google_analytics: UA-127764295-1

# Gems
plugins:
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5


